Numpy is one of the most important packages in python

In [7]:
import numpy as np #it is default to import numpy as np

In [8]:
num_list=[i for i in range(20)]
print(num_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [9]:
num_list+20 # does not work

TypeError: can only concatenate list (not "int") to list

In [10]:
for i in range(len(num_list)):
    num_list[i]+=20 #equals to num_list[i]=num_list[i] + 20
print(num_list)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]


In [11]:
num_list_two=num_list*2
print(num_list_two)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]


In [12]:
num_list_two=[]
for n in num_list:
    num_list_two.append(n * 2)
print(num_list_two)

[40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78]


In [13]:
num_list=np.arange(20)
print(num_list)
print(num_list+20)
print(num_list*2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [16]:

#x=0
#y=0
#z=0
s0=np.array([0,0])
v0=np.array([10,10])
a=np.array([0,-9.81])

#v=v0+a*t
#s=s0 + v0*t + 1/2 * a*t**2


def v(t):
    return v0+a*t 

def s(t):
    return s0 + v0*t + 1/2 * a* t**2

# at the end if
#s[1]=0
#0=s0 + v0*t + 1/2 * a* t**2
#t**2 + (2*v0/a) *t  + 2*s0/a = 0

#x=-p/2 +/- sqrt(p*p/4 - q)

t1=-(v0/a) - np.sqrt((v0/a)**2 - 2*s0/a)
t2=-(v0/a) + np.sqrt((v0/a)**2 - 2*s0/a)
print(t1)
print(t2)
t_fin=t2[1]
t_fin

[nan  0.]
[       nan 2.03873598]


<ipython-input-16-b51775aa259a>:25: RuntimeWarning: divide by zero encountered in true_divide
  t1=-(v0/a) - np.sqrt((v0/a)**2 - 2*s0/a)
<ipython-input-16-b51775aa259a>:25: RuntimeWarning: invalid value encountered in true_divide
  t1=-(v0/a) - np.sqrt((v0/a)**2 - 2*s0/a)
<ipython-input-16-b51775aa259a>:26: RuntimeWarning: divide by zero encountered in true_divide
  t2=-(v0/a) + np.sqrt((v0/a)**2 - 2*s0/a)
<ipython-input-16-b51775aa259a>:26: RuntimeWarning: invalid value encountered in true_divide
  t2=-(v0/a) + np.sqrt((v0/a)**2 - 2*s0/a)


2.038735983690112

In [17]:
for t in np.linspace(0,t_fin,10):
    print("v({:.2f})={}\ns({:.2f})={}\n".format(t,v(t).round(2),t,s(t).round(2)))


v(0.00)=[10. 10.]
s(0.00)=[0. 0.]

v(0.23)=[10.    7.78]
s(0.23)=[2.27 2.01]

v(0.45)=[10.    5.56]
s(0.45)=[4.53 3.52]

v(0.68)=[10.    3.33]
s(0.68)=[6.8  4.53]

v(0.91)=[10.    1.11]
s(0.91)=[9.06 5.03]

v(1.13)=[10.   -1.11]
s(1.13)=[11.33  5.03]

v(1.36)=[10.   -3.33]
s(1.36)=[13.59  4.53]

v(1.59)=[10.   -5.56]
s(1.59)=[15.86  3.52]

v(1.81)=[10.   -7.78]
s(1.81)=[18.12  2.01]

v(2.04)=[ 10. -10.]
s(2.04)=[20.39  0.  ]

